version: '1.0'
services:
  app:
    image: client
    container_name: tms-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tms_db

  db:
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: tms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./data/data.sql:/docker-entrypoint-initdb.d/1_init.sql
      - db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db-data: